/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HostModeProhibitedImport } from './routes/host-mode/prohibited'
import { Route as HostModePrivateImport } from './routes/host-mode/private'
import { Route as HostModeGuestImport } from './routes/host-mode/guest'
import { Route as ClientConnectProhibitedImport } from './routes/client-connect/prohibited'
import { Route as ClientConnectPrivatePrivateSessionImport } from './routes/client-connect/private/$privateSession'
import { Route as ClientConnectGuestSessionImport } from './routes/client-connect/guest/$session'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HostModeProhibitedRoute = HostModeProhibitedImport.update({
  id: '/host-mode/prohibited',
  path: '/host-mode/prohibited',
  getParentRoute: () => rootRoute,
} as any)

const HostModePrivateRoute = HostModePrivateImport.update({
  id: '/host-mode/private',
  path: '/host-mode/private',
  getParentRoute: () => rootRoute,
} as any)

const HostModeGuestRoute = HostModeGuestImport.update({
  id: '/host-mode/guest',
  path: '/host-mode/guest',
  getParentRoute: () => rootRoute,
} as any)

const ClientConnectProhibitedRoute = ClientConnectProhibitedImport.update({
  id: '/client-connect/prohibited',
  path: '/client-connect/prohibited',
  getParentRoute: () => rootRoute,
} as any)

const ClientConnectPrivatePrivateSessionRoute =
  ClientConnectPrivatePrivateSessionImport.update({
    id: '/client-connect/private/$privateSession',
    path: '/client-connect/private/$privateSession',
    getParentRoute: () => rootRoute,
  } as any)

const ClientConnectGuestSessionRoute = ClientConnectGuestSessionImport.update({
  id: '/client-connect/guest/$session',
  path: '/client-connect/guest/$session',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/client-connect/prohibited': {
      id: '/client-connect/prohibited'
      path: '/client-connect/prohibited'
      fullPath: '/client-connect/prohibited'
      preLoaderRoute: typeof ClientConnectProhibitedImport
      parentRoute: typeof rootRoute
    }
    '/host-mode/guest': {
      id: '/host-mode/guest'
      path: '/host-mode/guest'
      fullPath: '/host-mode/guest'
      preLoaderRoute: typeof HostModeGuestImport
      parentRoute: typeof rootRoute
    }
    '/host-mode/private': {
      id: '/host-mode/private'
      path: '/host-mode/private'
      fullPath: '/host-mode/private'
      preLoaderRoute: typeof HostModePrivateImport
      parentRoute: typeof rootRoute
    }
    '/host-mode/prohibited': {
      id: '/host-mode/prohibited'
      path: '/host-mode/prohibited'
      fullPath: '/host-mode/prohibited'
      preLoaderRoute: typeof HostModeProhibitedImport
      parentRoute: typeof rootRoute
    }
    '/client-connect/guest/$session': {
      id: '/client-connect/guest/$session'
      path: '/client-connect/guest/$session'
      fullPath: '/client-connect/guest/$session'
      preLoaderRoute: typeof ClientConnectGuestSessionImport
      parentRoute: typeof rootRoute
    }
    '/client-connect/private/$privateSession': {
      id: '/client-connect/private/$privateSession'
      path: '/client-connect/private/$privateSession'
      fullPath: '/client-connect/private/$privateSession'
      preLoaderRoute: typeof ClientConnectPrivatePrivateSessionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-connect/prohibited': typeof ClientConnectProhibitedRoute
  '/host-mode/guest': typeof HostModeGuestRoute
  '/host-mode/private': typeof HostModePrivateRoute
  '/host-mode/prohibited': typeof HostModeProhibitedRoute
  '/client-connect/guest/$session': typeof ClientConnectGuestSessionRoute
  '/client-connect/private/$privateSession': typeof ClientConnectPrivatePrivateSessionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-connect/prohibited': typeof ClientConnectProhibitedRoute
  '/host-mode/guest': typeof HostModeGuestRoute
  '/host-mode/private': typeof HostModePrivateRoute
  '/host-mode/prohibited': typeof HostModeProhibitedRoute
  '/client-connect/guest/$session': typeof ClientConnectGuestSessionRoute
  '/client-connect/private/$privateSession': typeof ClientConnectPrivatePrivateSessionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/client-connect/prohibited': typeof ClientConnectProhibitedRoute
  '/host-mode/guest': typeof HostModeGuestRoute
  '/host-mode/private': typeof HostModePrivateRoute
  '/host-mode/prohibited': typeof HostModeProhibitedRoute
  '/client-connect/guest/$session': typeof ClientConnectGuestSessionRoute
  '/client-connect/private/$privateSession': typeof ClientConnectPrivatePrivateSessionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-connect/prohibited'
    | '/host-mode/guest'
    | '/host-mode/private'
    | '/host-mode/prohibited'
    | '/client-connect/guest/$session'
    | '/client-connect/private/$privateSession'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-connect/prohibited'
    | '/host-mode/guest'
    | '/host-mode/private'
    | '/host-mode/prohibited'
    | '/client-connect/guest/$session'
    | '/client-connect/private/$privateSession'
  id:
    | '__root__'
    | '/'
    | '/client-connect/prohibited'
    | '/host-mode/guest'
    | '/host-mode/private'
    | '/host-mode/prohibited'
    | '/client-connect/guest/$session'
    | '/client-connect/private/$privateSession'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientConnectProhibitedRoute: typeof ClientConnectProhibitedRoute
  HostModeGuestRoute: typeof HostModeGuestRoute
  HostModePrivateRoute: typeof HostModePrivateRoute
  HostModeProhibitedRoute: typeof HostModeProhibitedRoute
  ClientConnectGuestSessionRoute: typeof ClientConnectGuestSessionRoute
  ClientConnectPrivatePrivateSessionRoute: typeof ClientConnectPrivatePrivateSessionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientConnectProhibitedRoute: ClientConnectProhibitedRoute,
  HostModeGuestRoute: HostModeGuestRoute,
  HostModePrivateRoute: HostModePrivateRoute,
  HostModeProhibitedRoute: HostModeProhibitedRoute,
  ClientConnectGuestSessionRoute: ClientConnectGuestSessionRoute,
  ClientConnectPrivatePrivateSessionRoute:
    ClientConnectPrivatePrivateSessionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/client-connect/prohibited",
        "/host-mode/guest",
        "/host-mode/private",
        "/host-mode/prohibited",
        "/client-connect/guest/$session",
        "/client-connect/private/$privateSession"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/client-connect/prohibited": {
      "filePath": "client-connect/prohibited.tsx"
    },
    "/host-mode/guest": {
      "filePath": "host-mode/guest.tsx"
    },
    "/host-mode/private": {
      "filePath": "host-mode/private.tsx"
    },
    "/host-mode/prohibited": {
      "filePath": "host-mode/prohibited.tsx"
    },
    "/client-connect/guest/$session": {
      "filePath": "client-connect/guest/$session.tsx"
    },
    "/client-connect/private/$privateSession": {
      "filePath": "client-connect/private/$privateSession.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
